import RecurringTransaction from "../models/RecurringTransaction.js";
import Transaction from "../models/Transaction.js";

const toStartOfDay = (value) => {
  const date = new Date(value);
  date.setUTCHours(0, 0, 0, 0);
  return date;
};

const addInterval = (dateValue, interval) => {
  const date = new Date(dateValue);

  if (interval === "daily") {
    date.setUTCDate(date.getUTCDate() + 1);
    return date;
  }

  if (interval === "weekly") {
    date.setUTCDate(date.getUTCDate() + 7);
    return date;
  }

  date.setUTCMonth(date.getUTCMonth() + 1);
  return date;
};

const syncRecurringTransactions = async (userId) => {
  const recurringItems = await RecurringTransaction.find({ userId, active: true }).sort({ nextRunDate: 1 });
  const today = toStartOfDay(new Date());
  let createdCount = 0;
  const createdPlans = [];

  for (const item of recurringItems) {
    let runDate = toStartOfDay(item.nextRunDate);
    let itemCreatedCount = 0;
    let guard = 0;

    while (runDate <= today && guard < 90) {
      const dayStart = new Date(runDate);
      const dayEnd = new Date(runDate);
      dayEnd.setUTCHours(23, 59, 59, 999);

      const existingTransactions = await Transaction.find({
        userId,
        recurringSourceId: item._id,
        date: {
          $gte: dayStart,
          $lte: dayEnd,
        },
      });

      if (existingTransactions.length === 0) {
        await Transaction.create({
          userId,
          type: item.type,
          category: item.category,
          amount: item.amount,
          date: runDate,
          note: item.note || `${item.name} (recurring)`,
          recurringSourceId: item._id,
          isAutoGenerated: true,
        });
        createdCount += 1;
        itemCreatedCount += 1;
      } else if (existingTransactions.length > 1) {
        const [, ...duplicates] = existingTransactions.sort((a, b) => a.createdAt - b.createdAt);
        await Transaction.deleteMany({
          _id: { $in: duplicates.map((entry) => entry._id) },
        });
      }

      runDate = addInterval(runDate, item.interval);
      guard += 1;
    }

    if (runDate.getTime() !== new Date(item.nextRunDate).getTime()) {
      item.nextRunDate = runDate;
      await item.save();
    }

    if (itemCreatedCount > 0) {
      createdPlans.push({ id: item._id.toString(), name: item.name, count: itemCreatedCount });
    }
  }

  return { createdCount, createdPlans };
};

export { addInterval, syncRecurringTransactions, toStartOfDay };
