import Transaction from "../models/Transaction.js";
import { syncRecurringTransactions } from "../utils/recurring.js";

const getDashboardSummary = async (req, res, next) => {
  try {
    await syncRecurringTransactions(req.user._id);
    const transactions = await Transaction.find({ userId: req.user._id }).sort({ date: -1 });

    const summary = transactions.reduce(
      (acc, transaction) => {
        if (transaction.type === "income") {
          acc.totalIncome += transaction.amount;
        } else {
          acc.totalExpenses += transaction.amount;
        }

        return acc;
      },
      {
        totalIncome: 0,
        totalExpenses: 0,
      }
    );

    const totalBalance = summary.totalIncome - summary.totalExpenses;
    const recentTransactions = transactions.slice(0, 5);

    res.json({
      totalBalance,
      totalIncome: summary.totalIncome,
      totalExpenses: summary.totalExpenses,
      savingsRate: summary.totalIncome ? ((totalBalance / summary.totalIncome) * 100).toFixed(1) : "0.0",
      autoGeneratedCount: transactions.filter((item) => item.isAutoGenerated).length,
      recentTransactions,
    });
  } catch (error) {
    next(error);
  }
};

export { getDashboardSummary };
