import { stringify } from "csv-stringify/sync";

import Transaction from "../models/Transaction.js";
import { syncRecurringTransactions } from "../utils/recurring.js";

const formatMonth = (value) => {
  const [year, month] = value.split("-");
  return new Date(Number(year), Number(month) - 1).toLocaleString("en-US", {
    month: "short",
    year: "numeric",
  });
};

const getReportOverview = async (req, res, next) => {
  try {
    await syncRecurringTransactions(req.user._id);
    const transactions = await Transaction.find({ userId: req.user._id }).sort({ date: 1 });

    const categoryMap = {};
    const monthlyMap = {};

    transactions.forEach((transaction) => {
      const month = transaction.date.toISOString().slice(0, 7);

      if (!monthlyMap[month]) {
        monthlyMap[month] = { month, income: 0, expense: 0 };
      }

      if (transaction.type === "expense") {
        categoryMap[transaction.category] = (categoryMap[transaction.category] || 0) + transaction.amount;
        monthlyMap[month].expense += transaction.amount;
      } else {
        monthlyMap[month].income += transaction.amount;
      }
    });

    const categoryBreakdown = Object.entries(categoryMap)
      .map(([category, amount]) => ({ category, amount }))
      .sort((a, b) => b.amount - a.amount);

    const monthlyTrends = Object.values(monthlyMap).map((item) => ({
      ...item,
      label: formatMonth(item.month),
      balance: item.income - item.expense,
    }));

    res.json({
      categoryBreakdown,
      monthlyTrends,
      incomeVsExpense: monthlyTrends.map((item) => ({
        label: item.label,
        income: item.income,
        expense: item.expense,
      })),
    });
  } catch (error) {
    next(error);
  }
};

const exportTransactionsCsv = async (req, res, next) => {
  try {
    await syncRecurringTransactions(req.user._id);
    const transactions = await Transaction.find({ userId: req.user._id }).sort({ date: -1, createdAt: -1 });
    const records = transactions.map((transaction) => ({
      date: transaction.date.toISOString().slice(0, 10),
      type: transaction.type,
      category: transaction.category,
      amount: transaction.amount,
      note: transaction.note,
      source: transaction.isAutoGenerated ? "recurring" : "manual",
    }));

    const csv = stringify(records, {
      header: true,
      columns: ["date", "type", "category", "amount", "note", "source"],
    });

    res.setHeader("Content-Type", "text/csv");
    res.setHeader("Content-Disposition", "attachment; filename=wealthwave-transactions.csv");
    res.send(csv);
  } catch (error) {
    next(error);
  }
};

export { exportTransactionsCsv, getReportOverview };
