import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

import api from "../api/client";

const downloadCsvExport = async () => {
  const response = await api.get("/reports/export/transactions.csv", {
    responseType: "blob",
  });
  const blobUrl = URL.createObjectURL(response.data);
  const link = document.createElement("a");
  link.href = blobUrl;
  link.download = "wealthwave-transactions.csv";
  link.click();
  URL.revokeObjectURL(blobUrl);
};

const downloadPdfReport = ({ budgets, reports, summary, transactions }) => {
  const pdf = new jsPDF();
  pdf.setFontSize(20);
  pdf.text("WealthWave Financial Report", 14, 20);
  pdf.setFontSize(11);
  pdf.text(`Balance: Rs. ${Number(summary.totalBalance).toLocaleString()}`, 14, 32);
  pdf.text(`Income: Rs. ${Number(summary.totalIncome).toLocaleString()}`, 14, 39);
  pdf.text(`Expenses: Rs. ${Number(summary.totalExpenses).toLocaleString()}`, 14, 46);
  pdf.text(`Savings Rate: ${summary.savingsRate}%`, 14, 53);

  autoTable(pdf, {
    head: [["Category", "Spent"]],
    body: reports.categoryBreakdown.map((item) => [item.category, `Rs. ${Number(item.amount).toLocaleString()}`]),
    startY: 62,
    theme: "grid",
  });

  autoTable(pdf, {
    head: [["Budget", "Spent", "Limit", "Status"]],
    body: budgets.map((item) => [
      item.category,
      `Rs. ${Number(item.spent).toLocaleString()}`,
      `Rs. ${Number(item.limit).toLocaleString()}`,
      item.exceeded ? "Exceeded" : "On track",
    ]),
    startY: pdf.lastAutoTable.finalY + 10,
    theme: "grid",
  });

  autoTable(pdf, {
    head: [["Date", "Type", "Category", "Amount", "Source"]],
    body: transactions.slice(0, 12).map((item) => [
      new Date(item.date).toLocaleDateString(),
      item.type,
      item.category,
      `Rs. ${Number(item.amount).toLocaleString()}`,
      item.isAutoGenerated ? "Recurring" : "Manual",
    ]),
    startY: pdf.lastAutoTable.finalY + 10,
    theme: "striped",
  });

  pdf.save("wealthwave-report.pdf");
};

export { downloadCsvExport, downloadPdfReport };
