const TransactionList = ({ transactions, onDelete }) => (
  <section className="panel" id="transactions">
    <div className="panel-header">
      <div>
        <span className="activity-text">Activity</span>
        <h2 className="activity-subtext">Recent transactions</h2>
      </div>
    </div>

    <div className="transaction-list">
      {transactions.length === 0 ? (
        <p className="empty-state">No transactions yet. Add your first income or expense above.</p>
      ) : (
        transactions.map((transaction) => (
            <article className="transaction-row" key={transaction._id}>
              <div>
                <strong>{transaction.category}</strong>
                <p>
                  {transaction.note || "No note added"}
                  {transaction.isAutoGenerated ? " · Added from recurring plan" : ""}
                </p>
              </div>
            <div className="transaction-meta">
              <span className={transaction.type === "income" ? "income-text" : "expense-text"}>
                {transaction.type === "income" ? "+" : "-"} Rs. {Number(transaction.amount).toLocaleString()}
              </span>
              <small>{new Date(transaction.date).toLocaleDateString()}</small>
              <button className="ghost-button danger-text" onClick={() => onDelete(transaction._id)}>
                Delete
              </button>
            </div>
          </article>
        ))
      )}
    </div>
  </section>
);

export default TransactionList;
